version: '1'

services:
  web:
    build: ./services/web
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/web/:/usr/src/app/
    expose:
      - 5000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dima
      - POSTGRES_PASSWORD=dima
      - POSTGRES_DB=incomes

  nginx:
    build: ./services/nginx
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
